# -*- coding: utf-8 -*-
"""Employee Attrition Problem Definition and Planning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVFcLWbGlx2RlO0eYnPKCH1eWnQJkgkx
"""

# ================================
# 1. IMPORT LIBRARIES
# ================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully!")

# ================================
# 2. UPLOAD DATASET
# ================================

from google.colab import files

uploaded = files.upload()

# ================================
# 3. LOAD DATASET
# ================================

file_name = "WA_Fn-UseC_-HR-Employee-Attrition.csv"

df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

# ================================
# 4. FIRST 5 ROWS
# ================================

df.head()

# ================================
# 5. BUSINESS UNDERSTANDING
# ================================

print("""
BUSINESS PROBLEM STATEMENT

Employee attrition is an important HR problem in which employees leave
an organization. High employee attrition can increase recruitment costs,
training costs, workload on existing employees, and loss of experienced
employees.

The objective of this project is to analyze employee data and identify
factors associated with employee attrition. The analysis can help HR
teams understand employee retention issues and support better
retention strategies.
""")

# ================================
# 6. DATASET UNDERSTANDING
# ================================

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

# ================================
# 7. DATA TYPES
# ================================

df.info()

# ================================
# 8. STATISTICAL SUMMARY
# ================================

df.describe()

# ================================
# 9. TARGET VARIABLE
# ================================

target = "Attrition"

print("Target Variable:", target)
print("\nTarget Variable Values:")
print(df[target].value_counts())

# ================================
# 10. ATTRITION DISTRIBUTION
# ================================

attrition_counts = df["Attrition"].value_counts()

plt.figure(figsize=(7,5))

sns.countplot(data=df, x="Attrition")

plt.title("Employee Attrition Distribution")
plt.xlabel("Attrition")
plt.ylabel("Number of Employees")

plt.show()

print(attrition_counts)

# ================================
# 11. ATTRITION PERCENTAGE
# ================================

attrition_percentage = df["Attrition"].value_counts(normalize=True) * 100

print("Attrition Percentage:")
print(attrition_percentage.round(2))

# ================================
# 12. MISSING VALUE ANALYSIS
# ================================

missing_values = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": missing_values.values
})

missing_table = missing_table.sort_values(
    by="Missing Values",
    ascending=False
)

missing_table

# ================================
# 13. DUPLICATE CHECK
# ================================

duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

# ================================
# 13. DUPLICATE CHECK
# ================================

duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

# ================================
# 14. FEATURE TYPES
# ================================

numerical_features = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = df.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

print("\nNumber of Numerical Features:", len(numerical_features))
print("Number of Categorical Features:", len(categorical_features))

# ================================
# 15. FEATURE DICTIONARY
# ================================

feature_dictionary = pd.DataFrame({
    "Feature": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Unique Values": [df[col].nunique() for col in df.columns],
    "Missing Values": [df[col].isnull().sum() for col in df.columns]
})

feature_dictionary

# ================================
# 16. NUMERICAL FEATURE DISTRIBUTION
# ================================

df[numerical_features].hist(
    figsize=(18, 15),
    bins=20
)

plt.suptitle(
    "Distribution of Numerical Features",
    fontsize=16
)

plt.tight_layout()
plt.show()

# ================================
# 17. CATEGORICAL FEATURE DISTRIBUTION
# ================================

important_categorical = [
    "BusinessTravel",
    "Department",
    "EducationField",
    "JobRole",
    "MaritalStatus",
    "OverTime",
    "Gender"
]

for col in important_categorical:
    plt.figure(figsize=(8,5))

    sns.countplot(
        data=df,
        x=col,
        hue="Attrition"
    )

    plt.title(f"{col} vs Attrition")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# ================================
# 18. AGE VS ATTRITION
# ================================

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Attrition",
    y="Age"
)

plt.title("Age Distribution by Attrition")
plt.show()

# ================================
# 19. MONTHLY INCOME VS ATTRITION
# ================================

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Attrition",
    y="MonthlyIncome"
)

plt.title("Monthly Income by Attrition")
plt.show()

# ================================
# 20. JOB SATISFACTION VS ATTRITION
# ================================

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="JobSatisfaction",
    hue="Attrition"
)

plt.title("Job Satisfaction vs Attrition")
plt.xlabel("Job Satisfaction")
plt.ylabel("Number of Employees")

plt.show()

# ================================
# 21. OVERTIME VS ATTRITION
# ================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="OverTime",
    hue="Attrition"
)

plt.title("Overtime vs Employee Attrition")
plt.xlabel("Overtime")
plt.ylabel("Number of Employees")

plt.show()

# ================================
# 22. JOB ROLE VS ATTRITION
# ================================

plt.figure(figsize=(12,6))

sns.countplot(
    data=df,
    x="JobRole",
    hue="Attrition"
)

plt.title("Job Role vs Employee Attrition")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

# ================================
# 23. CORRELATION MATRIX
# ================================

correlation_matrix = df[numerical_features].corr()

plt.figure(figsize=(18,14))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Matrix")

plt.show()

# ================================
# 24. ATTRITION CORRELATION
# ================================

df["Attrition_Numeric"] = df["Attrition"].map({
    "Yes": 1,
    "No": 0
})

attrition_corr = df.corr(
    numeric_only=True
)["Attrition_Numeric"].sort_values(
    ascending=False
)

print("Features correlated with Attrition:")
print(attrition_corr)

# ================================
# 25. TOP CORRELATED FEATURES
# ================================

top_features = attrition_corr.drop(
    "Attrition_Numeric"
).abs().sort_values(
    ascending=False
).head(10)

print("Top 10 features associated with Attrition:")
print(top_features)

# ================================
# 26. BUSINESS KPIs
# ================================

total_employees = len(df)

employees_left = (df["Attrition"] == "Yes").sum()

employees_stayed = (df["Attrition"] == "No").sum()

attrition_rate = (
    employees_left / total_employees
) * 100

print("Business KPIs")
print("--------------------------------")
print("Total Employees:", total_employees)
print("Employees Left:", employees_left)
print("Employees Stayed:", employees_stayed)
print("Overall Attrition Rate:", round(attrition_rate, 2), "%")

# ================================
# 27. DEPARTMENT-WISE ATTRITION
# ================================

department_attrition = pd.crosstab(
    df["Department"],
    df["Attrition"],
    normalize="index"
) * 100

department_attrition

# ================================
# 28. JOB ROLE ATTRITION RATE
# ================================

jobrole_attrition = pd.crosstab(
    df["JobRole"],
    df["Attrition"],
    normalize="index"
) * 100

jobrole_attrition.sort_values(
    by="Yes",
    ascending=False
)

# ================================
# 29. OVERTIME ATTRITION RATE
# ================================

overtime_attrition = pd.crosstab(
    df["OverTime"],
    df["Attrition"],
    normalize="index"
) * 100

overtime_attrition

# ================================
# 30. PROBLEM FORMULATION
# ================================

print("""
PROBLEM FORMULATION

Problem:
Predict whether an employee is likely to leave the organization.

Target Variable:
Attrition

Target Classes:
Yes - Employee left the organization
No  - Employee stayed in the organization

Problem Type:
Binary Classification

Business Objective:
Identify factors related to employee attrition so that HR teams
can develop appropriate employee retention strategies.
""")

# ================================
# 31. ETHICAL CONSIDERATIONS
# ================================

print("""
ETHICAL CONSIDERATIONS

1. Employee privacy must be protected.
2. Employee data should not be shared without authorization.
3. The model should not unfairly discriminate against employees.
4. Sensitive employee information should be handled carefully.
5. Predictions should support HR decisions rather than automatically
   making employment decisions.
6. The analysis should be transparent and explainable.
7. Data should be used only for legitimate business purposes.
""")

# ================================
# 32. PROJECT WORKFLOW
# ================================

workflow = """
Business Understanding
        ↓
Dataset Collection
        ↓
Dataset Understanding
        ↓
Data Cleaning
        ↓
Exploratory Data Analysis
        ↓
Feature Analysis
        ↓
Problem Formulation
        ↓
Model Development
        ↓
Model Evaluation
        ↓
Business Interpretation
        ↓
Employee Retention Strategy
"""

print(workflow)

# ================================
# 33. PROJECT ROADMAP
# ================================

roadmap = pd.DataFrame({
    "Phase": [
        "Business Understanding",
        "Dataset Understanding",
        "Data Cleaning",
        "EDA",
        "Problem Formulation",
        "Model Development",
        "Model Evaluation",
        "Business Recommendations"
    ],

    "Objective": [
        "Understand employee attrition problem",
        "Understand dataset and features",
        "Prepare clean data",
        "Identify important patterns",
        "Define prediction problem",
        "Build classification model",
        "Evaluate model performance",
        "Suggest retention strategies"
    ]
})

roadmap

# ================================
# 34. FINAL DATASET SUMMARY
# ================================

print("FINAL DATASET SUMMARY")
print("==============================")

print("Dataset Shape:", df.shape)

print("\nTarget Variable: Attrition")

print("\nAttrition Distribution:")
print(df["Attrition"].value_counts())

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nNumerical Features:", len(numerical_features))

print("Categorical Features:", len(categorical_features))

print("\nOverall Attrition Rate:",
      round(attrition_rate, 2), "%")

# ================================
# 35. CONCLUSION
# ================================

print("""
CONCLUSION

This project analyzed an employee attrition dataset to understand
the factors associated with employees leaving an organization.

The analysis included dataset understanding, feature identification,
missing-value analysis, feature distributions, attrition distribution,
and correlation analysis.

The results can help HR teams understand employee attrition patterns
and develop better employee retention strategies.

The next phase of the project can use machine learning classification
models to predict employee attrition.
""")

